version: '3.8'
services:
  clamd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3310:3310"
    volumes:
      - type: volume
        source: clamd_socket
        target: /var/run/clamav
        volume:
          nocopy: false
      - type: volume
        source: virus_db
        target: /var/lib/clamav
        volume:
          nocopy: false
  freshclam:
    build:
      context: .
      dockerfile: Dockerfile
    # command: freshclam -d --stdout --foreground -c 4
    command: tail -f /dev/null
    volumes:
      - type: volume
        source: clamd_socket
        target: /var/run/clamav
        volume:
          nocopy: false
      - type: volume
        source: virus_db
        target: /var/lib/clamav
        volume:
          nocopy: false

volumes:
  clamd_socket: {}
  virus_db: {}
