version: '3.8'
services:
  http-server:
    build:
      context: clamd-http-server/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      CLAMD_SERVER: "clamd"
      CLAMD_PORT: "3310"
  clamd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3310:3310"
    healthcheck:
      test: ["CMD-SHELL", "(sleep 0.5; echo PING) | nc -v -w 1 127.0.0.1 3310"]
      interval: 10s
      retries: 3
      start_period: 40s
    volumes:
      - type: volume
        source: clamd_socket
        target: /var/run/clamav
        volume:
          nocopy: false
      - type: volume
        source: virus_db
        target: /var/lib/clamav
        volume:
          nocopy: false
  freshclam:
    build:
      context: .
      dockerfile: Dockerfile
    command: freshclam -d --stdout --foreground -c 24
    volumes:
      - type: volume
        source: clamd_socket
        target: /var/run/clamav
        volume:
          nocopy: false
      - type: volume
        source: virus_db
        target: /var/lib/clamav
        volume:
          nocopy: false

volumes:
  clamd_socket: {}
  virus_db: {}
